### PR TITLE
Feat/redux

### PR DESCRIPTION
**Pull request by happyflower4**
- Introduce redux for state management
- Upgrade to Preact X
- Bug fixes and usability improvements

### CODE REVIEW

**Comment by happyflower4** [comment]
@aishraj Can you check if you can successfully build the project now? This should be good to merge if everything looks good on your side.

**Comment by aishraj** [comment]
Sure! I'll try to build it today on the server

**Comment by aishraj** [comment]
@happyflower4 
I see that there is a mismatch between the node version required to build this and what is in the container's Dockerfile.
```
~/akshara-project/parijat-frontend$ docker build .
Sending build context to Docker daemon    895kB
Step 1/7 : FROM node:carbon-alpine
 ---> 2b8fcdc6230a
Step 2/7 : ADD . /frontend
 ---> 0d7d499487d0
Step 3/7 : WORKDIR /frontend
 ---> Running in 307d8eaf837e
Removing intermediate container 307d8eaf837e
 ---> eec5fbe46ead
Step 4/7 : RUN yarn
 ---> Running in dff51619aa67
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
error file-loader@6.0.0: The engine "node" is incompatible with this module. Expected version ">= 10.13.0". Got "8.17.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn' returned a non-zero code: 1

```
Can you confirm if you can build the container?

**Comment by happyflower4** [comment]
@aishraj The issue should be fixed now. The production server was broken, and Node version had to be increased. 

Should the change regarding DigitalOcean be in this too?

**Comment by aishraj** [comment]
Deployed to production.

**Pull request merged**
